export const campgroundCatalog = {
    'recreation.gov': [
        {
            id: '232358',
            name: 'Outlet Campground',
            area: 'Redfish Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'East side of Redfish Lake, right on lake.',
            image: 'outlet_campground_map.jpg',
        },
        {
            id: '232085',
            name: 'Point Campground',
            area: 'Redfish Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'West side, on Redfish Lake, next to lodge. Smaller Campground.',
            image: 'point_campground_map.jpg',
        },
        {
            id: '232050',
            name: 'Glacier View Campground',
            area: 'Redfish Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'North side of Redfish Lake, right off of lake, walking distance.',
            image: 'glacier_view_campground_map.jpg',
        },
        {
            id: '234150',
            name: 'Sunny Gulch Campground',
            area: 'Redfish Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'Off of highway right across from Redfish Lake, but not walking distance.',
            image: 'sunny_gulch_campground_map1.jpg',
        },
        {
            id: '232087',
            name: 'Rainbow Point Campground',
            area: 'Cascade',
            site: 'recreation.gov',
            type: 'campground',
            description: 'On Cascade Lake, large site, recommended by Matty B.',
            image: 'rainbow_point_map.jpg',
        },
        {
            id: '233858',
            name: 'Stanley Lake Campground',
            area: 'Stanley Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'At Stanley Lake, "favorites" are all campsites on shoreline.',
            image: 'stanley_lake_campground_map.jpg',
        },
        {
            id: '232169',
            name: 'Mountain View Campground',
            area: 'Lowman',
            site: 'recreation.gov',
            type: 'campground',
            description: 'Favorite sites are right on river',
            image: 'mountain_view_campground_map.jpg',
        },
        {
            id: '232098',
            name: 'Shoreline Campground',
            area: 'Warm Lake',
            site: 'recreation.gov',
            type: 'campground',
            description: 'North Shore of Warm Lake',
            image: 'shoreline_campground_map.jpg',
        },
        {
            id: '233348',
            name: 'Redfish Cabin',
            area: 'Redfish Cabin',
            site: 'recreation.gov',
            type: 'cabin',
            description: 'Cabin only available during fall and winter.',
            image: 'redfish_cabin_map.jpg',
        },
    ],
};
