export const sites = {
    'recreation.gov': [
        {
            name: 'Shoreline Campground',
            area: 'Warm Lake',
            type: 'recreation.gov',
            id: '232085',
            favorites: ['010', '013', '025'],
            worthwhile: [],
            description: 'North Shore of Warm Lake',
        },
        {
            name: 'Point Campground',
            area: 'Redfish Lake',
            type: 'recreation.gov',
            id: '232085',
            favorites: ['012', '014', '016'],
            worthwhile: [],
            description: 'West side of Redfish Lake, close to lodge. Smaller Campground.',
        },
        {
            name: 'Redfish Cabin',
            area: 'Redfish Lake',
            type: 'recreation.gov',
            id: '233348',
            favorites: ['RF01'],
            worthwhile: [],
            description: 'Cabin only available duriung fall and winter.',
        },
        {
            name: 'Glacier View Campground',
            area: 'Redfish Lake',
            type: 'recreation.gov',
            id: '232050',
            favorites: ['016', '014', '012', '003'],
            worthwhile: [],
            description: 'North side of Redfish Lake, off of lake, but still close.',
        },
        {
            name: 'Outlet Campground',
            area: 'Redfish Lake',
            type: 'recreation.gov',
            id: '232358',
            favorites: ['013', '015', '011', '008'],
            worthwhile: [],
            description: 'East side of Redfish Lake, right on lake.',
        },
        {
            name: 'Sunny Gulch Campground',
            area: 'Redfish Lake',
            type: 'recreation.gov',
            id: '234150',
            favorites: ['026', '027'],
            worthwhile: [],
            description: 'Off of highway right across from Redfish Lake, but not walking distance.',
        },
        {
            name: 'Mountain View Campground',
            area: 'Lowman',
            type: 'recreation.gov',
            id: '232169',
            favorites: ['014', '015'],
            worthwhile: ['012', '011', '010', '008', '006'],
            description: 'Favorite sites are right on river',
        },
    ]
}